# Generated by Django 3.2.5 on 2021-07-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210711_1946'),
        ('course', '0003_auto_20210724_1320'),
    ]

    operations = [
    ]
